### ISSUE TITLE
Pipez pipes duplicate inserted items

### ISSUE THREAD

**Issue by benbenlaw** [AlmostReliable/summoningrituals-forge#14]
### Version

summoningrituals-1.19.2-2.0.1

### Describe the bug!

pipez pipes will insert the items but not take it from a chest making the items duplicatable 

https://youtu.be/04CyuuUBlFQ

Recipe is show inside the seaopolis 2 modpack

### Additional Context

Yes

### Modifications

Seaopolis 2 modpack 

https://www.curseforge.com/minecraft/modpacks/seaopolis-2

### Did the issue happen in singleplayer or on a server?

Both

**Comment by rlnt** [comment]
~~I mean I could fix this quite easily but I would honestly prefer if Pipez did an adjustment to their odd insertion logic that is only based on item stack sizes which is extremely error-prone.~~

~~I opened an issue for that [here](https://github.com/henkelmax/pipez/issues/167). If there is no response in the next few days (because they seem quite inactive), I will fix it myself. Sorry for the inconvenience.~~

As it turns out, this is a problem with original stack modification. Will fix this.

**Comment by benbenlaw** [comment]
many thanks
