### ISSUE TITLE
How to Clear the Summoning Table - wrong items are on the Table

### ISSUE THREAD

**Issue by gneumann333** [AlmostReliable/summoningrituals-forge#15]
### Version

FTB Legends of the Eyes 1.2.0

### Describe the bug!

Hi, i accedentialy put Items on thew summoning Table and now i dont know how to get the off it again.
Umong the Items are my best Sword and Pickaxe and i would like to get them back
I have tried Shift left and right click.
The Alatar says unbreakable...

### Additional Context

Yes

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
The items can be pulled back out by shift + right-clicking. However, this doesn't work when you have something in your off-hand with a secondary use like a shield. Try completely removing any item from your hands and shift + right-click again. It should work then.

This issue has been fixed in a more recent version of the mod but the pack didn't update yet.

**Comment by gneumann333** [comment]
Thank you, that worked.
I forgot my Emotional Support Bear (Totem of undying) in my Off - hand
