### ISSUE TITLE
block placement dupe

### ISSUE THREAD

**Issue by Sunekaer** [AlmostReliable/summoningrituals-forge#2]
### Version

1.0.0

### Describe the bug!

Puts blocks in the altar, but also places it
https://cdn.floatingmonkey.dev/screenshots/2022/09/16/1663360859_javaw.mp4

### Additional Context

Yes

### Modifications

*Edit by Relentless:*
[Modlist](https://cdn.floatingmonkey.dev/screenshots/2022/09/17/modlist.html)

### Did the issue happen in singleplayer or on a server?

Both

**Comment by rlnt** [comment]
https://user-images.githubusercontent.com/16513358/190805829-9c458605-ec82-4178-b979-15b3b08cd0f0.mp4

I used the latest build I have on CurseForge, I am on a dedicated server in survival mode and I can't reproduce this.<br>
It looks like GitHub messed up your modlist? I am pretty sure those are not all mods. Either way, there must be some kind of mod conflict. I also debugged the interaction handling with the altar and everything works fine even on a server.

I am quite confused why it says "Can't break" for you. For me, that mod looks like Jade which I am also using and it doesn't say that for me when looking at the altar so my guess is you have a build from the currently pending PR. Could that be the case? I didn't merge it yet because it has bugs so there is no way to obtain a build without compiling it yourself.

**Comment by wchen1990** [comment]
Doubt it's from the PR since I explicitly labelled the new block as "Indestructible Summoning Altar" in the lang file and none of the changes touched the item handling code. Just guessing but could be related to the override of the deprecated `use` method and maybe some mod conflict does something strange with that function.

Also, for what it's worth, tested on the branch PR #1 is on and can't reproduce it either.

**Comment by rlnt** [comment]
My guess for the usage of the PR branch originates from the right-click logic which is done inside a Forge event and specifically handles the normal altar block only. Since the PR introduced a new block, the right-click logic would not work correctly for it, especially with blocks.

The overriding of the `use` method is completely fine and normal. That's the way you do it. Mojangs use of deprecation is just flawed because they use it for methods that should not be called but are perfectly fine to override.

I also think this might be a mod conflict of something cancelling the player interaction event but that would require binary search from the pack devs and is probably not something on the mod side that requires fixing.

**Comment by Sunekaer** [comment]
I also used the build from CF.
Its saying cant break because i changed the destroySpeed & explosionResistance via kubejs
Heres the mod list done another way: https://cdn.floatingmonkey.dev/screenshots/2022/09/17/modlist.html

<blockquote></blockquote>

**Comment by Sunekaer** [comment]
Okay so after binary search:

ChiselsBits-forge-1.18.2-1.2.114-universal.jar
summoningrituals-1.18.2-1.0.0.jar

**Comment by rlnt** [comment]
Thanks for the report and the binary search. This has been fixed and will be available in the next update.

The next release also features an Indestructible Altar if you want to use that instead of making the normal block indestructible via KubeJS.
