### ISSUE TITLE
Crash with Blue Skies

### ISSUE THREAD

**Issue by hainkiwanki** [AlmostReliable/summoningrituals-forge#5]
### Version

1.18.2

### Crash Report

https://pastebin.com/P78tjcnn

### Additional Context

No

### Did the crash happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
For future reference, if anyone finds this:<br>
JEI does not support multiple mods registering a new ingredient type for the same target class. For the block below the altar, I registered an ingredient type that targets block states and Blue Skies seems to do the same thing (I say "seems" because they decided to make their mod closed source .-.) which results in a crash.<br>
The new approach to fix this is to use another target class e.g. a wrapped block state to avoid having the same target.
