### ISSUE TITLE
[BUG] Adding multiple Sacrifices break recipes

### ISSUE THREAD

**Issue by TheonlyTazz** [AlmostReliable/summoningrituals-forge#8]
### Version

summoningrituals-1.18.2-1.1.3.jar

### Describe the bug!

Basicly trying to add 3 withers to sacrifice
using 
`.sacrifice('3x minecraft:wither')`
will cause it not to work
![image](https://user-images.githubusercontent.com/3908847/195410115-daa9d18c-df21-4c8e-a7f2-1e9ac9d0645f.png)

adding 3x, 
`.sacrifice('minecraft:wither')`
![image](https://user-images.githubusercontent.com/3908847/195410507-62c96ee2-01fb-4d28-afff-e69ef28f845b.png)

it does add the sacrifices, but only kills one

### Crash Report

no crash report

### Log

no log?

### Additional Context

Yes

### Modifications

tested this in Inferno, havent tested on a isolated instance

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
This is normal because the `'3x  minecraft:wither'` is invalid syntax. I mentioned this part on the [wiki here](https://github.com/AlmostReliable/summoningrituals-forge/wiki/Recipes#defining-sacrifices). The way you add multiple sacrifices is different than that for items. So if you want to avoid having the sacrifice statement 3 times, you can use `.sacrifice('minecraft:wither', 3)`.

The reason behind that is that I use native KubeJS bindings for items that provide the syntactic sugar like `'3x stone'` but since there is no entity wrapper in KubeJS, the implementation works a bit differently.

Edit: the part with the wrapper is actually explained on mob outputs but it's the same for sacrifices and I listed examples for this case https://github.com/AlmostReliable/summoningrituals-forge/wiki/Recipes#mob-outputs

**Comment by TheonlyTazz** [comment]
seems im just blind, thanks relentless
